### ISSUE TITLE
create_swapchain: TypeError: function takes exactly 3 arguments (5 given)

### ISSUE THREAD

**Issue by mpumpa** [rdeioris/compushady#8]
Hello,
i was trying the Swapchain example from your readme:
```
import glfw
from compushady import HEAP_UPLOAD, Buffer, Swapchain, Texture2D
from compushady.formats import B8G8R8A8_UNORM
import platform
import random

glfw.init()
# we do not want implicit OpenGL!
glfw.window_hint(glfw.CLIENT_API, glfw.NO_API)

target = Texture2D(256, 256, B8G8R8A8_UNORM)
random_buffer = Buffer(target.size, HEAP_UPLOAD)

window = glfw.create_window(
    target.width, target.height, 'Random', None, None)

if platform.system() == 'Windows':
    swapchain = Swapchain(glfw.get_win32_window(
        window), B8G8R8A8_UNORM, 3)
else:
    swapchain = Swapchain((glfw.get_x11_display(), glfw.get_x11_window(
        window)), B8G8R8A8_UNORM, 3)

while not glfw.window_should_close(window):
    glfw.poll_events()
    random_buffer.upload(bytes([random.randint(0, 255), random.randint(
        0, 255), random.randint(0, 255), 255]) * (target.size // 4))
    random_buffer.copy_to(target)
    swapchain.present(target)

swapchain = None  # this ensures the swapchain is destroyed before the window

glfw.terminate()
```
but i got his error:
```
  File "testing.py", line 18, in <module>
    swapchain = Swapchain(glfw.get_win32_window(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\venv\Lib\site-packages\compushady\__init__.py", line 199, in __init__
    self.handle = self.device.create_swapchain(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: function takes exactly 3 arguments (5 given)
```

i can't look deep enough into your code to determine what went wrong, any help is appreciated.
I am using Python 3.11, compushady 0.17.2, Windows 64 bit

If it is of any interest, i got here because i was looking foreward to play around with this repository but encountered this error:
https://github.com/HenBOMB/Py-Slime-Simulation/tree/main

**Comment by rdeioris** [comment]
Are you using the pypi package or you are compiling from sources? That error would make sense if you are using the 'samplers' branch

**Comment by mpumpa** [comment]
I used the PyPi version, just via `pip install compushady`
i just tried `pip install git+https://github.com/rdeioris/compushady.git@main ` which fails to build a wheel  
then i installed the wheel posted in Issue #3, but on execution it throws the same error

**Comment by rdeioris** [comment]
Hi, there is a problem with the tarballs uploaded on pypi. You can manually clone the repo and just setup.py install it. I whould be able to upload new wheels on pypi (included the ones for python 3.12) by the end of the week

**Comment by rdeioris** [comment]
@mpumpa Pypi versions have been updated. I will wait for your confirmation before closing the issue.

**Comment by mpumpa** [comment]
yes, thank you. with version 0.17.3 it works as expected. Thanks for the help.
